# Generated by Django 4.2.11 on 2024-03-20 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InsurancePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                ("expiration_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Vehicles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("auto", "Auto"),
                            ("motocicleta", "Motocicleta"),
                            ("bicicleta", "Bicicleta"),
                            ("camioneta", "Camioneta"),
                            ("yate", "Yate"),
                            ("velero", "Velero"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("color", models.CharField(max_length=50)),
                ("license_plate", models.CharField(max_length=20, unique=True)),
                (
                    "insurance_policy",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle",
                        to="access.insurancepolicy",
                    ),
                ),
            ],
        ),
    ]
