# Generated by Django 4.2.11 on 2024-03-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="vehicles",
            constraint=models.UniqueConstraint(
                fields=("vehicle_type", "license_plate"), name="unique_vehicle"
            ),
        ),
    ]
