# Generated by Django 4.2.11 on 2024-03-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0002_vehicles_unique_vehicle"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="vehicles",
            name="unique_vehicle",
        ),
        migrations.RemoveField(
            model_name="vehicles",
            name="id",
        ),
        migrations.AlterField(
            model_name="vehicles",
            name="license_plate",
            field=models.CharField(
                max_length=20, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
