# Generated by Django 4.2.11 on 2024-03-20 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0004_vehicles_license_plate_vehicle_type_unique"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="vehicles",
            name="license_plate_vehicle_type_unique",
        ),
    ]
