# Generated by Django 4.2.11 on 2024-03-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0005_remove_vehicles_license_plate_vehicle_type_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insurancepolicy",
            name="expiration_date",
            field=models.DateTimeField(),
        ),
    ]
