# Generated by Django 4.2.11 on 2024-03-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0006_alter_insurancepolicy_expiration_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insurancepolicy",
            name="expiration_date",
            field=models.DateField(),
        ),
    ]
